/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

/**
 *
 * @author sergiany e carol
 */
public class MenuTabelas extends javax.swing.JFrame {

	/**
	 * Creates new form MenuTabelas
	 */
	public MenuTabelas() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		btImovel = new javax.swing.JButton();
		btCorretora = new javax.swing.JButton();
		btCliente = new javax.swing.JButton();
		btFuncionario = new javax.swing.JButton();
		btVenda = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		btSair = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		btImovel.setText("Imovel");
		btImovel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btImovelActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.ipadx = 22;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 187, 0, 0);
		getContentPane().add(btImovel, gridBagConstraints);

		btCorretora.setText("Corretora");
		btCorretora.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btCorretoraActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.ipadx = 8;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
		getContentPane().add(btCorretora, gridBagConstraints);

		btCliente.setText("Cliente");
		btCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btClienteActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.ipadx = 22;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
		getContentPane().add(btCliente, gridBagConstraints);

		btFuncionario.setText("Funcionario");
		btFuncionario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btFuncionarioActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
		getContentPane().add(btFuncionario, gridBagConstraints);

		btVenda.setText("Venda");
		btVenda.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btVendaActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.ipadx = 24;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
		getContentPane().add(btVenda, gridBagConstraints);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/janelas/imagem.png"))); // NOI18N
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(60, 73, 0, 20);
		getContentPane().add(jLabel1, gridBagConstraints);

		btSair.setText("Sair");
		btSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btSairActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.ipadx = 36;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 187, 32, 0);
		getContentPane().add(btSair, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btImovelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btImovelActionPerformed
		// TODO add your handling code here:
		TelaMenuImovel tmi = new TelaMenuImovel();
		tmi.setVisible(true);
		dispose();
	}// GEN-LAST:event_btImovelActionPerformed

	private void btCorretoraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btCorretoraActionPerformed
		// TODO add your handling code here:
		TelaMenuCorretora tmc = new TelaMenuCorretora();
		tmc.setVisible(true);
		dispose();
	}// GEN-LAST:event_btCorretoraActionPerformed

	private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btClienteActionPerformed
		// TODO add your handling code here:
		TelaMenuCliente tmcl = new TelaMenuCliente();
		tmcl.setVisible(true);
		dispose();
	}// GEN-LAST:event_btClienteActionPerformed

	private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btFuncionarioActionPerformed
		// TODO add your handling code here:
		TelaMenuFuncionario tmf = new TelaMenuFuncionario();
		tmf.setVisible(true);
		dispose();
	}// GEN-LAST:event_btFuncionarioActionPerformed

	private void btVendaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btVendaActionPerformed
		// TODO add your handling code here:
		TelaMenuVenda tmv = new TelaMenuVenda();
		tmv.setVisible(true);
		dispose();
	}// GEN-LAST:event_btVendaActionPerformed

	private void btSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSairActionPerformed
		// TODO add your handling code here:
		System.exit(0);
	}// GEN-LAST:event_btSairActionPerformed

	// /**
	// * @param args the command line arguments
	// */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(MenuTabelas.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(MenuTabelas.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(MenuTabelas.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(MenuTabelas.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new MenuTabelas().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btCliente;
	private javax.swing.JButton btCorretora;
	private javax.swing.JButton btFuncionario;
	private javax.swing.JButton btImovel;
	private javax.swing.JButton btSair;
	private javax.swing.JButton btVenda;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
