/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import br.com.dao.CorretoraDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Carolina
 */
public class TelaExcluirCorretora extends javax.swing.JFrame {

	/**
	 * Creates new form TelaExcluirCorretora
	 */
	CorretoraDao dao = new CorretoraDao();

	public TelaExcluirCorretora() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		txtExcluir = new javax.swing.JTextField();
		btLimpar = new javax.swing.JButton();
		btExcluir = new javax.swing.JButton();
		btSair = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabel6.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/janelas/imagem.png"))); // NOI18N
		jLabel6.setText("Excluir Corretora");
		jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 5;
		gridBagConstraints.ipadx = 16;
		gridBagConstraints.ipady = -26;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 24);
		getContentPane().add(jLabel6, gridBagConstraints);

		jLabel1.setText("Digite o nome da corretora:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(27, 111, 0, 0);
		getContentPane().add(jLabel1, gridBagConstraints);

		txtExcluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtExcluirActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 111, 0, 0);
		getContentPane().add(txtExcluir, gridBagConstraints);

		btLimpar.setText("Limpar");
		btLimpar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btLimparActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 111, 22, 0);
		getContentPane().add(btLimpar, gridBagConstraints);

		btExcluir.setText("Excluir");
		btExcluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btExcluirActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 44, 22, 0);
		getContentPane().add(btExcluir, gridBagConstraints);

		btSair.setText("Voltar");
		btSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btSairActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 142, 22, 0);
		getContentPane().add(btSair, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btLimparActionPerformed
		// TODO add your handling code here:
		txtExcluir.setText("");
	}// GEN-LAST:event_btLimparActionPerformed

	private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btExcluirActionPerformed
		// TODO add your handling code here:
		String a = txtExcluir.getText(); // pega oq foi digitado
		if ("".equals(a)) {
			dispose();
			JOptionPane.showMessageDialog(null, "Digite o nome de uma corretora!");
			TelaExcluirCorretora tbc = new TelaExcluirCorretora();
			tbc.setVisible(true);

		} else {
			dao.excluir(a); // chama o metodo para excluir convertendo-o para inteiro
			txtExcluir.setText(""); // limpar
			JOptionPane.showMessageDialog(null, "Corretora excluida!\n");
			dispose();// fecha a tela
		}
	}// GEN-LAST:event_btExcluirActionPerformed

	private void btSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSairActionPerformed
		// TODO add your handling code here:
		MenuTabelas mt = new MenuTabelas();
		mt.setVisible(true);
		dispose();

	}// GEN-LAST:event_btSairActionPerformed

	private void txtExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtExcluirActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtExcluirActionPerformed

	// /**
	// * @param args the command line arguments
	// */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(TelaExcluirCorretora.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(TelaExcluirCorretora.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(TelaExcluirCorretora.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(TelaExcluirCorretora.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new TelaExcluirCorretora().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btExcluir;
	private javax.swing.JButton btLimpar;
	private javax.swing.JButton btSair;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField txtExcluir;
	// End of variables declaration//GEN-END:variables
}
