/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

/**
 *
 * @author sergiany e carol
 */
public class TelaMenuImovel extends javax.swing.JFrame {

	/**
	 * Creates new form TelaMenuImovel
	 */
	public TelaMenuImovel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel6 = new javax.swing.JLabel();
		btInserir = new javax.swing.JButton();
		btVerTudo = new javax.swing.JButton();
		btAlterar = new javax.swing.JButton();
		btExcluir = new javax.swing.JButton();
		btVoltar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabel6.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/janelas/imagem.png"))); // NOI18N
		jLabel6.setText(" Menu");
		jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.ipadx = 102;
		gridBagConstraints.ipady = -26;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(29, 4, 0, 5);
		getContentPane().add(jLabel6, gridBagConstraints);

		btInserir.setText("Inserir");
		btInserir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btInserirActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.ipadx = 18;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 228, 0, 0);
		getContentPane().add(btInserir, gridBagConstraints);

		btVerTudo.setText("Ver Todos");
		btVerTudo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btVerTudoActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 228, 0, 0);
		getContentPane().add(btVerTudo, gridBagConstraints);

		btAlterar.setText("Alterar");
		btAlterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btAlterarActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.ipadx = 16;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 228, 0, 0);
		getContentPane().add(btAlterar, gridBagConstraints);

		btExcluir.setText("Excluir");
		btExcluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btExcluirActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.ipadx = 18;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 228, 0, 0);
		getContentPane().add(btExcluir, gridBagConstraints);

		btVoltar.setText("Voltar");
		btVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btVoltarActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.ipadx = 20;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 228, 29, 0);
		getContentPane().add(btVoltar, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btInserirActionPerformed
		// TODO add your handling code here:
		TelaInserirImovel telaInserirImovel = new TelaInserirImovel(); // chama a tela para inserir imovel
		telaInserirImovel.setVisible(true);
		dispose();
	}// GEN-LAST:event_btInserirActionPerformed

	private void btVerTudoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btVerTudoActionPerformed
		// TODO add your handling code here:
		TelaImprimeImovel tii = new TelaImprimeImovel();
		tii.setVisible(true);
		dispose();
	}// GEN-LAST:event_btVerTudoActionPerformed

	private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btAlterarActionPerformed
		// TODO add your handling code here:
		TelaAlterarImovel tai = new TelaAlterarImovel();
		tai.setVisible(true);
		dispose();
	}// GEN-LAST:event_btAlterarActionPerformed

	private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btExcluirActionPerformed
		// TODO add your handling code here:
		TelaExcluirImovel tei = new TelaExcluirImovel();
		tei.setVisible(true);
		dispose();
	}// GEN-LAST:event_btExcluirActionPerformed

	private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btVoltarActionPerformed
		// TODO add your handling code here:
		MenuTabelas mt = new MenuTabelas();
		mt.setVisible(true);
		dispose();
	}// GEN-LAST:event_btVoltarActionPerformed

	// /**
	// * @param args the command line arguments
	// */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(TelaMenuImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(TelaMenuImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(TelaMenuImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(TelaMenuImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new TelaMenuImovel().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btAlterar;
	private javax.swing.JButton btExcluir;
	private javax.swing.JButton btInserir;
	private javax.swing.JButton btVerTudo;
	private javax.swing.JButton btVoltar;
	private javax.swing.JLabel jLabel6;
	// End of variables declaration//GEN-END:variables
}
