/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import br.com.atrib.Imovel;
import br.com.dao.ImovelDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Carolina
 */
public class TelaInserirImovel extends javax.swing.JFrame {

	/**
	 * Creates new form TelaInserirImovel
	 */
	public TelaInserirImovel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		txtId_corretora = new javax.swing.JTextField();
		txtNome = new javax.swing.JTextField();
		txtPreco = new javax.swing.JTextField();
		txtQntd_banheiro = new javax.swing.JTextField();
		txtQntd_quartos = new javax.swing.JTextField();
		txtQntd_comodos = new javax.swing.JTextField();
		txtEndereco = new javax.swing.JTextField();
		txtCidade = new javax.swing.JTextField();
		txtTipo = new javax.swing.JTextField();
		btLimpar = new javax.swing.JButton();
		btSair = new javax.swing.JButton();
		btSalvar = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabel6.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/janelas/imagem.png"))); // NOI18N
		jLabel6.setText("Inserir Imóvel");
		jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 19;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(1, 110, 0, 0);
		getContentPane().add(jLabel6, gridBagConstraints);

		jLabel1.setText("Código da Corretora *:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 9;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(21, 120, 0, 0);
		getContentPane().add(jLabel1, gridBagConstraints);

		jLabel2.setText("Nome:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 120, 0, 0);
		getContentPane().add(jLabel2, gridBagConstraints);

		jLabel3.setText("Preço:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 120, 0, 0);
		getContentPane().add(jLabel3, gridBagConstraints);

		jLabel4.setText("Qntd de Banheiro:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 8;
		gridBagConstraints.gridwidth = 7;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 120, 0, 0);
		getContentPane().add(jLabel4, gridBagConstraints);

		jLabel5.setText("Qntd de Quartos:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 10;
		gridBagConstraints.gridwidth = 6;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(14, 120, 0, 0);
		getContentPane().add(jLabel5, gridBagConstraints);

		jLabel7.setText("Qntd de Cômodos:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 12;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 120, 0, 0);
		getContentPane().add(jLabel7, gridBagConstraints);

		jLabel8.setText("Endereço:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 14;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 120, 0, 0);
		getContentPane().add(jLabel8, gridBagConstraints);

		jLabel9.setText("Cidade:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 16;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 120, 0, 0);
		getContentPane().add(jLabel9, gridBagConstraints);

		jLabel10.setText("Tipo *:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 18;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 120, 0, 0);
		getContentPane().add(jLabel10, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 122);
		getContentPane().add(txtId_corretora, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtNome, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtPreco, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 8;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtQntd_banheiro, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 10;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 122);
		getContentPane().add(txtQntd_quartos, gridBagConstraints);

		txtQntd_comodos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtQntd_comodosActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 12;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtQntd_comodos, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 14;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtEndereco, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 16;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtCidade, gridBagConstraints);

		txtTipo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTipoActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 18;
		gridBagConstraints.gridwidth = 29;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 435;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 122);
		getContentPane().add(txtTipo, gridBagConstraints);

		btLimpar.setText("Limpar");
		btLimpar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btLimparActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 20;
		gridBagConstraints.gridwidth = 5;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 120, 11, 0);
		getContentPane().add(btLimpar, gridBagConstraints);

		btSair.setText("Sair");
		btSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btSairActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 18;
		gridBagConstraints.gridy = 20;
		gridBagConstraints.gridwidth = 20;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 188, 11, 122);
		getContentPane().add(btSair, gridBagConstraints);

		btSalvar.setText("Salvar");
		btSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btSalvarActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 17;
		gridBagConstraints.gridy = 20;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 68, 11, 0);
		getContentPane().add(btSalvar, gridBagConstraints);

		jLabel11.setForeground(new java.awt.Color(255, 0, 0));
		jLabel11.setText("Sempre digitar os dados que contém o *");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 10;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(24, 120, 0, 0);
		getContentPane().add(jLabel11, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtQntd_comodosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtQntd_comodosActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtQntd_comodosActionPerformed

	private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTipoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtTipoActionPerformed

	private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSalvarActionPerformed
		// TODO add your handling code here:
		if ("".equals(txtTipo.getText()) || "".equals(txtId_corretora.getText())) {
			dispose();
			JOptionPane.showMessageDialog(null, "Ops, nao pode cadastrar sem o tipo ou sem a corretora!");
			TelaInserirImovel tbc = new TelaInserirImovel();
			tbc.setVisible(true);

		} else {
			Imovel s = new Imovel();
			s.setNome(txtNome.getText());
			s.setId_corretora(Integer.parseInt(txtId_corretora.getText()));
			s.setPreco(Float.parseFloat(txtPreco.getText()));
			s.setQtd_quarto(Integer.parseInt(txtQntd_quartos.getText()));
			s.setQtd_banheiro(Integer.parseInt(txtQntd_banheiro.getText()));
			s.setQtd_comodos(Integer.parseInt(txtQntd_comodos.getText()));
			s.setEndereco(txtEndereco.getText());
			s.setCidade(txtCidade.getText());
			s.setTipo(txtTipo.getText());

			ImovelDao dao = new ImovelDao();
			dao.inserir(s); // chama a fun�ao inserir, para inserir no banco de dados
			dispose();
			JOptionPane.showMessageDialog(null, "Imovel inserido\n");
			MenuTabelas mt = new MenuTabelas();
			mt.setVisible(true);
			dispose();
		}
	}// GEN-LAST:event_btSalvarActionPerformed

	private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btLimparActionPerformed
		// TODO add your handling code here:
		txtNome.setText("");
		txtCidade.setText("");
		txtEndereco.setText("");
		txtId_corretora.setText("");
		txtPreco.setText("");
		txtQntd_quartos.setText("");
		txtQntd_comodos.setText("");
		txtQntd_banheiro.setText("");
		txtTipo.setText("");
	}// GEN-LAST:event_btLimparActionPerformed

	private void btSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSairActionPerformed
		// TODO add your handling code here:
		MenuTabelas mt = new MenuTabelas();
		mt.setVisible(true);
		dispose();
	}// GEN-LAST:event_btSairActionPerformed

	// /**
	// * @param args the command line arguments
	// */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(TelaInserirImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(TelaInserirImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(TelaInserirImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(TelaInserirImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new TelaInserirImovel().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btLimpar;
	private javax.swing.JButton btSair;
	private javax.swing.JButton btSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField txtCidade;
	private javax.swing.JTextField txtEndereco;
	private javax.swing.JTextField txtId_corretora;
	private javax.swing.JTextField txtNome;
	private javax.swing.JTextField txtPreco;
	private javax.swing.JTextField txtQntd_banheiro;
	private javax.swing.JTextField txtQntd_comodos;
	private javax.swing.JTextField txtQntd_quartos;
	private javax.swing.JTextField txtTipo;
	// End of variables declaration//GEN-END:variables
}
