/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import br.com.atrib.Imovel;
import br.com.dao.ImovelDao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Ana Carolina
 */
public class TelaDigitarImovel extends javax.swing.JFrame {

	/**
	 * Creates new form TelaDigitarImovel
	 */
	ImovelDao dao = new ImovelDao();
	TelaAlterarImovel tai = new TelaAlterarImovel();

	public TelaDigitarImovel() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		txtPreco = new javax.swing.JTextField();
		txtQntd_quartos = new javax.swing.JTextField();
		txtQntd_banheiros = new javax.swing.JTextField();
		txtQntd_comodos = new javax.swing.JTextField();
		txtEndereco = new javax.swing.JTextField();
		txtCidade = new javax.swing.JTextField();
		btLimpar = new javax.swing.JButton();
		btAlterar = new javax.swing.JButton();
		btSair = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabel6.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/janelas/imagem.png"))); // NOI18N
		jLabel6.setText("Alterar Imóvel");
		jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 15;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		getContentPane().add(jLabel6, gridBagConstraints);

		jLabel1.setText("Preço:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(21, 62, 0, 0);
		getContentPane().add(jLabel1, gridBagConstraints);

		jLabel2.setText("Quartos:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 62, 0, 0);
		getContentPane().add(jLabel2, gridBagConstraints);

		jLabel3.setText("Banheiros:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 6;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 62, 0, 0);
		getContentPane().add(jLabel3, gridBagConstraints);

		jLabel4.setText("Cômodos:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 62, 0, 0);
		getContentPane().add(jLabel4, gridBagConstraints);

		jLabel5.setText("Endereço:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 9;
		gridBagConstraints.gridwidth = 5;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(14, 62, 0, 0);
		getContentPane().add(jLabel5, gridBagConstraints);

		jLabel7.setText("Cidade:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 11;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(9, 62, 0, 0);
		getContentPane().add(jLabel7, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 416;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
		getContentPane().add(txtPreco, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 418;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
		getContentPane().add(txtQntd_quartos, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 416;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
		getContentPane().add(txtQntd_banheiros, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 413;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 7, 0, 0);
		getContentPane().add(txtQntd_comodos, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 9;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 412;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 8, 0, 0);
		getContentPane().add(txtEndereco, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 11;
		gridBagConstraints.gridwidth = 8;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 412;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
		getContentPane().add(txtCidade, gridBagConstraints);

		btLimpar.setText("Limpar");
		btLimpar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btLimparActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 13;
		gridBagConstraints.gridwidth = 7;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(27, 62, 70, 0);
		getContentPane().add(btLimpar, gridBagConstraints);

		btAlterar.setText("Alterar");
		btAlterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btAlterarActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 12;
		gridBagConstraints.gridy = 13;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(27, 155, 70, 0);
		getContentPane().add(btAlterar, gridBagConstraints);

		btSair.setText("Voltar");
		btSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btSairActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 13;
		gridBagConstraints.gridy = 13;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(27, 133, 70, 0);
		getContentPane().add(btSair, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btLimparActionPerformed
		// TODO add your handling code here:
		txtCidade.setText("");
		txtEndereco.setText("");
		txtPreco.setText("");
		txtQntd_banheiros.setText("");
		txtQntd_comodos.setText("");
		txtQntd_quartos.setText("");

	}// GEN-LAST:event_btLimparActionPerformed

	private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btAlterarActionPerformed
		// TODO add your handling code here:
		try {
			Imovel s = new Imovel();
			String a = tai.txtId_imovel.getText();
			s.setId_imovel(Integer.parseInt(a));
			s.setPreco(Float.parseFloat(txtPreco.getText()));
			s.setQtd_quarto(Integer.parseInt(txtQntd_quartos.getText()));
			s.setQtd_banheiro(Integer.parseInt(txtQntd_banheiros.getText()));
			s.setQtd_comodos(Integer.parseInt(txtQntd_comodos.getText()));
			s.setEndereco(txtEndereco.getText());
			s.setCidade(txtCidade.getText());
			// chama a funcao p alterar
			dao.altera(s);
			dispose();
			setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		} catch (Exception ex) {
			Logger.getLogger(TelaInserirImovel.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btAlterarActionPerformed

	private void btSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSairActionPerformed
		// TODO add your handling code here:
		MenuTabelas mt = new MenuTabelas();
		mt.setVisible(true);
		dispose();
	}// GEN-LAST:event_btSairActionPerformed

	// /**
	// * @param args the command line arguments
	// */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(TelaDigitarImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(TelaDigitarImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(TelaDigitarImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(TelaDigitarImovel.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new TelaDigitarImovel().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btAlterar;
	private javax.swing.JButton btLimpar;
	private javax.swing.JButton btSair;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField txtCidade;
	private javax.swing.JTextField txtEndereco;
	private javax.swing.JTextField txtPreco;
	private javax.swing.JTextField txtQntd_banheiros;
	private javax.swing.JTextField txtQntd_comodos;
	private javax.swing.JTextField txtQntd_quartos;
	// End of variables declaration//GEN-END:variables
}
